### ISSUE TITLE
Laravel IO 2.0

### ISSUE THREAD

**Issue by driesvints** [laravelio/portal#16]
This is a general overview of all the features that the new [laravel.io](http://laravel.io) website will have. We'll use this as an overview to check for things missing and to check off features which are completed.

Initial development is being handled by the core team to ensure that the conventions / vision are established. Should one feel like contributing in some way to the completion of this list, definitely comment first on the individual task.
### General
- [ ] Document coding conventions (#12)
- [ ] Decide on workflow for assets management and design tools (#11)
- [ ] Add Mandrill for email transaction (#24)
- [x] Add soft deletes to everything (#25)
- [x] Automate database backups  (#26)
- [ ] Add maintenance page (#28)
- [ ] Add google analytics (#29)
- [x] Add hosted by FortRabbit (#36)
- [ ] Contributors: create contributors page (#42)
- [ ] Contact: enable contact (#43)
- [ ] Add Laravel Weekly Subscription Form (#45)
### Homepage
- [ ] list featured blogs and forum posts (#22)
- [ ] define the site (#23)
### Users
- [x] Enable Github authentication
- [x] Add user profile page (#18)
- [ ] Add dashboard with subscribed forum threads (#20)
- [ ] Hide profile of banned user (#44)
### IRC
- [x] properly segment out pre auth and post auth chat (#47)
- [ ] Design chat page (#31)
### Articles
- [x] Allow users to create articles (#3)
- [ ] Add RSS feed (#5)
- [ ] Allow admins to lock articles (#6)
- [x] Integrate tagging system (#7)
- [x] Add Markdown editor (#8)
- [x] Enable comments (#9)
- [ ] Decide which stats should be kept (#21)
- [x] Design (#34)
- [x] Add Laravel version indicator (#39)
### Forums
- [ ] Determine starting sections (#48)
- [x] Add Markdown editor to posts (#13)
- [x] Stress test and optimize (#15)
- [ ] Allow users to subscribe to topics (#19)
- [x] Design (#32)
- [x] Create initial post explaining the site (#37)
- [ ] Old Forums: prepare for hibernation (#1)
- [ ] Old Forums: move them to an archive url (#41)
### Pastebin
- [ ] Create initial foundation (#17)
- [ ] Design (#33)
### Launch
- [x] Change all caching / sessions to memcached (#46)
- [ ] Last minute double-check of all sql queries loaded per page (#27)
- [ ] Browser test / site responsiveness test (#30) 
- [x] Upgrade hosting (#35)
- [ ] Send mailer (#40)
- [ ] Write article that explains the site (#38)
